FROM i386/debian

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get --yes --no-install-recommends install \
        linux-image-4.9.0-6-686 grub2 systemd \
        gcc make libc6-dev \
        wget \
        file vim \
    && \
    chsh -s /bin/bash && \
    echo "root:root" | chpasswd && \
    mkdir -p /etc/systemd/system/serial-getty@ttyS0.service.d/ && \
    systemctl enable serial-getty@ttyS0.service && \
    rm /lib/systemd/system/getty.target.wants/getty-static.service && \
    rm /etc/motd /etc/issue && \
    systemctl disable systemd-timesyncd.service && \
    systemctl disable apt-daily.timer && \
    systemctl disable apt-daily-upgrade.timer && \
    apt-get --yes clean && \
    cd /root/ && \
    wget http://www.math.utah.edu/~mayer/linux/nbench-byte-2.2.3.tar.gz && \
    tar xfv nbench-byte-2.2.3.tar.gz && \
    rm nbench-byte-2.2.3.tar.gz && \
    mv nbench-byte-2.2.3 bench && \
    cd bench && \
    make

COPY getty-noclear.conf getty-override.conf /etc/systemd/system/getty@tty1.service.d/
COPY getty-autologin-serial.conf /etc/systemd/system/serial-getty@ttyS0.service.d/
